# Generated by Django 2.1.5 on 2019-01-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='another_body',
        ),
    ]
