# Generated by Django 2.1.5 on 2019-01-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbs',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
