# Generated by Django 2.1.5 on 2019-01-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_thumbs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumbs',
        ),
    ]
